wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723395878
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 24
      - 37
      4: 3.12.4
      5: 0.17.6
      8:
      - 5
      13: linux-x86_64
K_epochs:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 64
ent_coef:
  desc: null
  value: 0.0791678723329548
eps_clip:
  desc: null
  value: 0.27216632541381214
gamma:
  desc: null
  value: 0.9522650241734938
lr:
  desc: null
  value: 0.0005924112644713218
vf_coef:
  desc: null
  value: 0.9976472078827908
